### PR TITLE
Professionalize font build process

### LINKED ISSUE #1: You should note that this is just the DOS 8x8 font with some glyphs added by Terry
It comes via FreeDOS.

Screenshot from 2022-11-07 08-18-28

Terry notes this in his docs. I have been thinking of writing a half joke half serious Unicode proposal for the unencoded characters and this came up when looking into the font's origin / history.

### LINKED ISSUE #2: No PostScript name specified
I have a patch for this, it makes the font impossible to use in many terminal emulators, e.g. xterm, kitty, etc.

### PR DESCRIPTION
**Pull request by ctrlcctrlv**
- Closes #1.
- Closes #2.

### CODE REVIEW

**Comment by rendello** [comment]
Looks good from what I can see @ctrlcctrlv, thanks!

This repo was a one-off, I spent about a dozen hours learning about fonts, pulling the bitmaps from TempleOS, using Bits 'n Picas, etc. I knew very little about fonts then and probably less, now that I've forgotten. I'm glad I randomly looked at the repo since Github never gave me notifications about the issues or PR. Teminal users will be glad to see the added support.

**Comment by ctrlcctrlv** [comment]
That's no problem, thanks for working on it.

**Comment by ctrlcctrlv** [comment]
If it's all the same to you, then, @rendello, for the sake of authenticity, and given the error I found which you made in #5, I want to dump Bits 'n Picas entirely from the build, and base the build off of Terry's original file `StdFont.HC.Z`, which I will just use a simple program to make into a BDF.

**Comment by rendello** [comment]
@ctrlcctrlv The repo is mainly for hosting the font files, so people can quickly grab them, so I don't mind if the build process is changed (or added, since I didn't have one). I remember using Bits 'n Picas for hours, but I can't honestly remember at all what I did with it or how I extracted the fonts in the first place. If you have a process that will improve the fonts people get, I don't imagine there'll be any issues with that. 

Realistically, I doubt many people will be running the build scripts / programs anyway if the fonts are available, unless they want to extract different fonts from a TempleOS fork, or something.

**Comment by ctrlcctrlv** [comment]
@rendello Gotcha, that's fine then. Yeah, nothing really wrong with Bits 'n Picas, I am mostly suggesting we move away from it as I want to do more advanced things (as discussed in #4) which it doesn't support.

**Pull request merged**
